all:
	g++ -o ../bin/colorpicker colorpicker.cpp ../class/RGBcolor.cpp ../class/Point.cpp -I../class
	g++ -o ../bin/kapalpesawat kapalpesawat.cpp ../class/DrawingObject.cpp ../class/FrameBuffer.cpp ../class/Point.cpp ../class/RGBcolor.cpp ../class/Pattern.cpp ../class/Object.cpp -I../class
	g++ -o ../bin/petaindonesia petaindonesia.cpp ../class/DrawingObject.cpp ../class/FrameBuffer.cpp ../class/Point.cpp ../class/RGBcolor.cpp ../class/Pattern.cpp ../class/Object.cpp ../class/Map.cpp -I../class